services:
  workspace:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    runtime: nvidia
    stdin_open: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../:/home/developer/ros2_ws/src:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib/wsl:/usr/lib/wsl
    devices:
      - /dev:/dev
    environment:
      - DISPLAY
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LIBVA_DRIVER_NAME=d3d12
      - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - LIBGL_ALWAYS_SOFTWARE=false